create database QuanLyCuaHangBanhKeo
on
(
	name = 'QuanLyCuaHangBanhKeo_Data',
	filename = 'D:\DaiHoc\DatabaseQuanLyCuaHangBanhKeo\QuanLyCuaHangBanhKeo_Data.MDF'
)
log on
(
	name = 'QuanLyCuaHangBanhKeo_Log',
	filename = 'D:\DaiHoc\DatabaseQuanLyCuaHangBanhKeo\QuanLyCuaHangBanhKeo_Log.LDF'
)

use QuanLyCuaHangBanhKeo

create table MatHang
(
	MAHANG NVARCHAR(50) NOT NULL CONSTRAINT pk_MatHang primary key(MAHANG),
	TENHANG NVARCHAR(50) NOT NULL,
	NHASX NVARCHAR(50) NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYSANXUAT DATE NULL,
	NGAYHETHAN DATE NULL,
	DONVITINH NVARCHAR(50) NULL,
	GIA NVARCHAR(50) NULL,
	MOTA NVARCHAR(500) NULL
)

Drop Table KhachHang
Select * from mathang
Select * from KhachHang
select * from taikhoan

SELECT SUM(CAST(TONGTIEN AS INT)) AS TOTAL FROM Giohang

SELECT MATAIKHOAN FROM TAIKHOAN WHERE TENTAIKHOAN LIKE 'DUCDUY'

INSERT INTO MatHang Values ('MH03',N'Hộp bánh quế',N'Công ty Hải Châu',300,'2022-12-20','2023-12-20',N'thùng','50000',N'Nổi tiếng với lớp bánh quy Vani  đặc trưng trứ danh. Bánh vị Vani 54g với lớp vỏ bánh thơm giòn cuộn cùng kem vani thơm béo.')
INSERT INTO MatHang Values ('MH04',N'Bánh kem sốt phủ',N'Công ty Hải Châu',300,'2022-10-01','2023-10-01',N'thùng','40000',N'Sản phẩm có hương vị thơm ngon, dạng que giòn tan, bọc  bên  ngoài một lớp kem dâu  hoặc kem sữa chocolate béo  ngậy, thơm ngon.')
INSERT INTO MatHang Values ('MH05',N'Kẹo nhân Cà phê ',N'Công ty Hải Châu',100,'2022-10-08','2024-10-08',N'hộp','30000',N'Kẹo được sản xuất theo công nghệ hiện đại của Thổ Nhĩ Kỳ. Quy trình sản xuất khép kín hoàn toàn từ khâu lựa chọn nguyên liệu cho tới đóng gói.')
INSERT INTO MatHang Values ('MH06',N'Bánh sừng bò ',N'Công ty Hải Châu',200,'2022-10-20','2023-10-20',N'thùng','90000',N'Bánh sừng bò (Croissant) là loại bánh mì ngọt có bơ với bột bánh bông xốp, nổi tiếng bởi hình dáng như mảnh trăng lưỡi liềm đặc trưng của loại bánh này.')

UPDATE MatHang SET MAHANG = 'MH03', TENHANG = N'Hộp bánh quế', NHASX = N'Công ty Hải Châu', SOLUONG = 300, NGAYSANXUAT = '2022-12-20', NGAYHETHAN = '2024-12-20', DONVITINH = N'thùng', GIA = '50000', MOTA = N'Nổi tiếng với lớp bánh quy Vani đặc trưng trứ danh. Bánh vị Vani 54g với lớp vỏ bánh thơm giòn cuộn cùng kem vani thơm béo.' WHERE MAHANG LIKE 'MH03'

create table GioHang
(
	STT INT IDENTITY(1,1) NOT NULL,
	MAHANG NVARCHAR(50) NOT NULL,
	MATAIKHOAN NVARCHAR(50) NOT NULL,
	TENHANG NVARCHAR(50) NULL,
	SOLUONG INT NULL,
	TONGTIEN NVARCHAR(50) NULL,
	CONSTRAINT pk_GioHang2
	PRIMARY KEY(STT),
	CONSTRAINT fk_GH2_MatHang FOREIGN KEY(MAHANG) REFERENCES MatHang(MAHANG),
	CONSTRAINT fk_GH2_KhachHang FOREIGN KEY(MATAIKHOAN) REFERENCES KhachHang(MATAIKHOAN)
)

create table GioHang
(
	STT INT IDENTITY(1,1) NOT NULL,
	MAHANG NVARCHAR(50) NOT NULL,
	TENHANG NVARCHAR(50) NULL,
	SOLUONG INT NULL,
	TONGTIEN NVARCHAR(50) NULL,
	CONSTRAINT pk_GioHang2
	PRIMARY KEY(STT),
	CONSTRAINT fk_GH2_MatHang FOREIGN KEY(MAHANG) REFERENCES MatHang(MAHANG),
)

Drop Table GioHang
Select * from giohang
Delete from giohang

select * from GioHang where MaTaiKhoan like 'TK02'

INSERT INTO GioHang SELECT MAHANG, TENHANG, SOLUONG - (SOLUONG - 1) , GIA FROM MatHang WHERE MAHANG = 'MH01'
INSERT INTO GioHang SELECT MAHANG, TENHANG, SOLUONG - (SOLUONG - 1) , GIA FROM MatHang WHERE MAHANG = 'MH02'

INSERT INTO GioHang SELECT mh.MAHANG, kh.MaTaiKhoan, mh.TENHANG, mh.SOLUONG - (SOLUONG - 1), mh.GIA FROM MatHang mh, KhachHang kh  WHERE mh.MAHANG = 'MH02' --and kh.MaTaiKhoan = 'TK02'

create trigger tg_them_giohang
on GioHang
	for insert
as
	UPDATE MatHang
	set MatHang.SOLUONG = MatHang.SOLUONG - inserted.SOLUONG
	from MatHang inner join inserted on
	MatHang.MAHANG = inserted.MAHANG

create trigger trg_giohang_update_soluong
on GioHang
	for UPDATE
as
	if UPDATE(SOLUONG)
	UPDATE MATHANG
	SET MATHANG.SOLUONG = MATHANG.SOLUONG -
	(SELECT SUM(inserted.SOLUONG - deleted.SOLUONG)
	FROM inserted INNER JOIN deleted
	ON inserted.STT= deleted.STT
	WHERE inserted.MAHANG = MATHANG.MAHANG)
	WHERE MATHANG.MAHANG IN (SELECT MAHANG FROM inserted)

create table PhanHoi
(
	HOTEN NVARCHAR(100) NULL,
	EMAIL NVARCHAR(50) NULL,
	NOIDUNG NVARCHAR(500) NULL
)

select * from PhanHoi
INSERT INTO PhanHoi Values (N'Chương Minh Hào',N'minhhao24902@gmail.com',N'Mặt hàng bánh quy bơ vừng rất ngon!')
delete from PhanHoi
drop table PhanHoi

create table HoaDon
(
	MAHD NVARCHAR(50) NOT NULL CONSTRAINT pk_HoaDon primary key(MAHD),
	NGAYLAP DATE NULL,
	SOLUONG INT NOT NULL,
	TONGTIEN NVARCHAR(50) NULL,
	MOTA NVARCHAR(500) NULL,
	MAHANG NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_HD_MatHang FOREIGN KEY(MAHANG) REFERENCES MatHang(MAHANG)
)


CREATE TABLE NhanVien
(
	MANHANVIEN NVARCHAR(50) NOT NULL CONSTRAINT pk_NhanVien PRIMARY KEY(MANHANVIEN),
	TENNHANVIEN NVARCHAR(50) NOT NULL,
	NAMSINH INT NOT NULL,
	GIOITINH CHAR(10) NOT NULL,
	DIENTHOAI NVARCHAR(50) NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	CHUCVU NVARCHAR(50) NOT NULL,
	LUONGCOBAN NVARCHAR(50) NULL
)

drop table nhanvien
select * from nhanvien

CREATE TABLE KhachHang
(
	MATAIKHOAN NVARCHAR(50) NOT NULL
	CONSTRAINT pk_KhachHang
	PRIMARY KEY(MATAIKHOAN),
	TENKHACHHANG NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	DIENTHOAI NVARCHAR(50) NULL,
	EMAIL NVARCHAR(50) NULL,
	NAMSINH DATE NULL,
	GIOITINH NVARCHAR(20),
)

select * from KhachHang
select * from TaiKhoan
drop table KHACHHANG
Delete from khachhang

Insert into khachhang values (N'TK02',N'Trần Đức Duy',N'Thủ Dầu Một, Bình Dương','03323102034','ducduy2409@gmail.com','2022-10-12','Nam')
Insert into khachhang values (N'TK03',N'Trần Duy Tùng',N'Biên Hoà, Đồng Nai','03323102034','duytung2409@gmail.com','2023-10-12','Nam')

CREATE TABLE NhaCungCap
(
	MANHACUNGCAP NVARCHAR(50) NOT NULL
	CONSTRAINT pk_NhaCungCap
	primary KEY(MANHACUNGCAP),
	TENNHACUNGCAP NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	DIENTHOAI NVARCHAR(50) NULL,
	EMAIL NVARCHAR(50) NULL,
)

CREATE TABLE PNhap
(
	MAPN NVARCHAR(50) NOT NULL
	CONSTRAINT pk_PNhap
	PRIMARY KEY(MAPN),
	MANHACUNGCAP NVARCHAR(50) NOT NULL,
	CONSTRAINT fk_PNhap_NhaCungCap
	FOREIGN KEY(MANHACUNGCAP)
	REFERENCES NhaCungCap(MANHACUNGCAP)
	ON DELETE CASCADE ON UPDATE CASCADE,
	MANHANVIEN NVARCHAR(50) NOT NULL
	CONSTRAINT fk_PNhap_Nhan_Vien
	FOREIGN KEY(MANHANVIEN)
	REFERENCES NhanVien(MANHANVIEN)
	ON DELETE CASCADE ON UPDATE CASCADE,
	NGAYNHAP DATETIME NOT NULL,
)

CREATE TABLE ChiTietPNhap
(
	MAPN NVARCHAR(50) NOT NULL,
	MAHANG NVARCHAR(50) NOT NULL,
	SLNHAP INT NOT NULL,
	THUE FLOAT,
	DONGIANHAP FLOAT NOT NULL,
	CONSTRAINT pk_CTPNhap
	PRIMARY KEY(MAPN,MAHANG),
	CONSTRAINT fk_CTPNhap_MatHang
	FOREIGN KEY (MAHANG)
	REFERENCES MatHang(MAHANG)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_CTPNhap_PNhap
	FOREIGN KEY(MAPN)
	REFERENCES PNhap(MAPN)
	ON DELETE CASCADE ON UPDATE CASCADE
)

create table TaiKhoan
(
	MATAIKHOAN NVARCHAR(50) NOT NULL CONSTRAINT pk_MaTaiKhoan primary key(MATAIKHOAN),
	TENTAIKHOAN NVARCHAR(50) NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	QUYEN INT NOT NULL,
	MOTAQUYEN NVARCHAR(50) NOT NULL,
)


--proc nha cung cap

CREATE PROC SP_INSERT_NHACUNGCAP
	@MANHACUNGCAP NVARCHAR(50),
	@TENNHACUNGCAP NVARCHAR(50),
	@DIACHI NVARCHAR(50),
	@DIENTHOAI NVARCHAR(50),
	@EMAIL NVARCHAR(50)
	AS
IF(NOT EXISTS(SELECT MANHACUNGCAP FROM NHACUNGCAP WHERE MANHACUNGCAP=@MANHACUNGCAP))
	INSERT INTO NHACUNGCAP VALUES (@MANHACUNGCAP,@TENNHACUNGCAP,@DIACHI,@DIENTHOAI,@EMAIL)
ELSE
	RAISERROR('DA TON MA NHA CUNG CAP NAY',12,1)
GO

CREATE PROC SP_UPDATE_NHACUNGCAP
@MANHACUNGCAP NVARCHAR(50),
@TENNHACUNGCAP NVARCHAR(50),
@DIACHI NVARCHAR(50),
@DIENTHOAI NVARCHAR(50),
@EMAIL NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MANHACUNGCAP FROM NHACUNGCAP WHERE MANHACUNGCAP=@MANHACUNGCAP))
	RAISERROR('KHONG TON TAI NHA CUNG CAP NAY',12,1)
ELSE
	UPDATE NHACUNGCAP SET TENNHACUNGCAP=@TENNHACUNGCAP,DIACHI=@DIACHI,DIENTHOAI=@DIENTHOAI,EMAIL=@EMAIL WHERE MANHACUNGCAP=@MANHACUNGCAP
	RAISERROR('DA TON TAI MA NHA CUNG CAP NAY',12,1)
GO

CREATE PROC SP_DELETE_NHACUNGCAP
@MANHACUNGCAP NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MANHACUNGCAP FROM NHACUNGCAP WHERE MANHACUNGCAP=@MANHACUNGCAP))
	RAISERROR('KHONG TON TAI NHA CUNG CAP NAY',12,1)
ELSE
	DELETE FROM NHACUNGCAP WHERE MANHACUNGCAP=@MANHACUNGCAP
GO

--proc khach hang

CREATE PROC SP_INSERT_KHACHANG
@MAKHACHHANG NVARCHAR(50),
@TENKHACHHANG NVARCHAR(50),
@DIACHI NVARCHAR(50),
@DIENTHOAI NVARCHAR(50),
@EMAIL NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MAKHACHHANG FROM KHACHHANG WHERE MAKHACHHANG=@MAKHACHHANG))
	INSERT INTO KHACHHANG VALUES (@MAKHACHHANG,@TENKHACHHANG,@DIACHI,@DIENTHOAI,@EMAIL)
ELSE
	RAISERROR('DA TON TAI MA KHACH HANG NAY!!',12,1)
GO

CREATE PROC SP_UPDATE_KHACHHANG
@MAKHACHHANG NVARCHAR(50),
@TENKHACHHANG NVARCHAR(50),
@DIACHI NVARCHAR(50),
@DIENTHOAI NVARCHAR(50),
@EMAIL NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MAKHACHHANG FROM KHACHHANG WHERE MAKHACHHANG=@MAKHACHHANG))
	RAISERROR('KHONG TON TAI KHACHHANGNAY',12,1)
ELSE
	UPDATE KHACHHANG SET TENKHACHHANG=@TENKHACHHANG,DIACHI=@DIACHI,DIENTHOAI=@DIENTHOAI,EMAIL=@EMAIL WHERE MAKHACHHANG=@MAKHACHHANG
GO

CREATE PROC SP_DELETE_KHACHHANG
@MAKHACHHANG NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MAKHACHHANG FROM KHACHHANG WHERE MAKHACHHANG=@MAKHACHHANG))
	RAISERROR('KHONG TON TAI KHACHHANGNAY',12,1)
ELSE
	DELETE FROM KHACHHANG WHERE MAKHACHHANG=@MAKHACHHANG
GO

--proc nhan vien
CREATE PROC SP_INSERT_NHANVIEN
@MANHANVIEN NVARCHAR(50),
@NAMSINH INT,
@TENNHANVIEN NVARCHAR(50),
@GIOITINH CHAR(10),
@DIENTHOAI NVARCHAR(50),
@DIACHI NVARCHAR(50),
@CHUCVU NVARCHAR(50),
@LUONGCOBAN NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MANHANVIEN FROM NHANVIEN WHERE MANHANVIEN=@MANHANVIEN))
	BEGIN
	INSERT INTO NHANVIEN VALUES (@MANHANVIEN, @TENNHANVIEN,@NAMSINH, @GIOITINH, @DIENTHOAI, @DIACHI, @CHUCVU, @LUONGCOBAN)
	END
ELSE
	RAISERROR('DA TON TAI MA NHAN VIEN NAY',12,1)
GO

CREATE PROC SP_UPDATE_NHANVIEN
@MANHANVIEN NVARCHAR(50),
@NAMSINH INT,
@TENNHANVIEN NVARCHAR(50),
@GIOITINH CHAR(10),
@DIENTHOAI NVARCHAR(50),
@DIACHI NVARCHAR(50),
@CHUCVU NVARCHAR(50),
@LUONGCOBAN NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MANHANVIEN FROM NHANVIEN WHERE MANHANVIEN=@MANHANVIEN))
	RAISERROR('CHUA CO MA NHAN VIEN NAY',12,1)
ELSE
	UPDATE NHANVIEN SET NAMSINH=@NAMSINH, TENNHANVIEN=@TENNHANVIEN, GIOITINH=@GIOITINH, DIENTHOAI=@DIENTHOAI, DIACHI=@DIACHI, CHUCVU=@CHUCVU, LUONGCOBAN=@LUONGCOBAN WHERE MANHANVIEN=@MANHANVIEN
GO

CREATE PROC SP_DELETE_NHANVIEN
@MANHANVIEN NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MANHANVIEN FROM NHANVIEN WHERE MANHANVIEN=@MANHANVIEN))
	RAISERROR('KHONG TON TAI NHAN VIEN NAY HOAC DA BI SA THAI',12,1)
ELSE
	DELETE FROM NHANVIEN WHERE MANHANVIEN=@MANHANVIEN
GO

--proc mat hang

CREATE PROC SP_INSERT_MATHANG
@MAHANG NVARCHAR(50),
@TENHANG NVARCHAR(50),
@NHASX NVARCHAR(50),
@SOLUONG INT,
@THONGTINBAOHANH NVARCHAR(100),
@DONVITINH NVARCHAR(50 ),
@MOTA NVARCHAR(100)
AS
IF NOT EXISTS(SELECT MAHANG FROM MATHANG WHERE MAHANG=@MAHANG)
BEGIN
	INSERT MATHANG VALUES(@MAHANG,@TENHANG,@NHASX,@SOLUONG,@THONGTINBAOHANH,@DONVITINH,@MOTA)
END 
ELSE
	RAISERROR('DA TON TAI MA HANG NAY',12,1)
GO

CREATE PROC SP_UPDATE_MATHANG
@MAHANG  NVARCHAR(50),
@TENHANG NVARCHAR(50 ),
@NHASX NVARCHAR(50),
@SOLUONG INT,
@THONGTINBAOHANH   NVARCHAR(50),
@DONVITINH NVARCHAR(50),
@MOTA  NVARCHAR(100)
AS
IF NOT EXISTS(SELECT MAHANG FROM MATHANG  WHERE MAHANG=@MAHANG)
	RAISERROR('KHONG CO MAT HANG NAY ', 12,1)
ELSE 
	UPDATE MATHANG SET TENHANG=@TENHANG, NHASX=@NHASX, SOLUONG=@SOLUONG,THONGTINBAOHANH=@THONGTINBAOHANH, DONVITINH=@DONVITINH,MOTA=@MOTA WHERE MAHANG=@MAHANG
GO

CREATE PROC SP_DELETE_MATHANG
@MAHANG NVARCHAR(50)
AS
IF(NOT EXISTS(SELECT MAHANG FROM MATHANG WHERE MAHANG=@MAHANG))
	RAISERROR('KHONG TON TAI MA HANG NAY',12,1)
ELSE
BEGIN
	IF((SELECT SOLUONG FROM MATHANG WHERE MAHANG=@MAHANG)>0)
		RAISERROR('KHONG THE XOA HANG NAY',12,1)
	ELSE
		DELETE FROM MATHANG WHERE(MAHANG=@MAHANG)
END


INSERT INTO MatHang
    (MAHANG, TENHANG, NHASX, SOLUONG, THONGTINBAOHANH, DONVITINH, MOTA)
VALUES
    ('MH02', 'Banh Chocopie', 'Cong ty Orio', '450', '2 nam', 'hop', 'Banh ngot ngon re');

SELECT * FROM MatHang
WHERE MAHANG = 'MH01'

DELETE FROM MATHANG
WHERE MAHANG = 'MH01'